DROP TABLE addresses;
DROP TABLE categories;    
DROP TABLE favorites;     
DROP TABLE jobs;          
DROP TABLE profiles;      
DROP TABLE users;         
DROP TABLE requests;      
DROP TABLE verifications; 
DROP TABLE job_payments; 
