version: '3'
services:

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - myapp

  api:
    build: . 
    image: fazilnbr/job-portal-project:1.1
    env_file:
      - .env
    ports: 
      - 8080:8080
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - myapp
volumes:
  db:
networks:
  myapp: