// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/account/verifyJWT": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Varify JWT of users",
                "operationId": "Varify admin JWT authentication",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email : ",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/activateusers": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "block users for admin",
                "operationId": "block users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id of User : ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/domain.Login"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/activateworkers": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "block workers for admin",
                "operationId": "block workers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id of User : ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/domain.Login"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/block": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "add job category for admin",
                "operationId": "add category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "category : ",
                        "name": "category",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/domain.Category"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/listallusers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "list all active users for admin",
                "operationId": "list all active users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/domain.Login"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/listallworkers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "list all active workers for admin",
                "operationId": "list all active workers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/domain.Login"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/listblockedusers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "list all blocked users for admin",
                "operationId": "list all blocked users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/domain.Login"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/listblockedworkers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "list all blocked workers for admin",
                "operationId": "list all blocked workers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/domain.Login"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/listnewusers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "list all new users for admin",
                "operationId": "list all new users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Name : ",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password : ",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/domain.Login"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/listnewworkers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "list all new workers for admin",
                "operationId": "list all new workers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Name : ",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password : ",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/domain.Login"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Edit profile for User",
                "operationId": "user edit profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Name : ",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Gender : ",
                        "name": "gender",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date Of Birth : ",
                        "name": "dateofbirth",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "House Name : ",
                        "name": "housename",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Place : ",
                        "name": "place",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Post : ",
                        "name": "post",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pin : ",
                        "name": "pin",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Contact Number : ",
                        "name": "contactnumber",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Email Id : ",
                        "name": "emailid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Photo : ",
                        "name": "photo",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/domain.Profile"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/account/verifyJWT": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Varify JWT of users",
                "operationId": "Varify JWT authentication",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email : ",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Login for users",
                "operationId": "login authentication",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Name : ",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password : ",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/domain.UserResponse"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/send/verification": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Send OTP varification mail to users",
                "operationId": "SendVerificationMail authentication",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email : ",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/domain.UserResponse"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/signup": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "SignUp for users",
                "operationId": "SignUp authentication",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Name : ",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password : ",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/domain.Login"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/verify/account": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Varify OTP of users",
                "operationId": "Varify OTP authentication",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email : ",
                        "name": "email",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OTP : ",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/woker/signup": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "SignUp for Workers",
                "operationId": "Worker SignUp authentication",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Name : ",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password : ",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/domain.Login"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/worker/account/verifyJWT": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Varify JWT of users",
                "operationId": "Varify worker JWT authentication",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email : ",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/worker/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Login for worker",
                "operationId": "worker login authentication",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Name : ",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password : ",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/domain.UserResponse"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/worker/send/verification": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Send OTP varification mail to worker",
                "operationId": "Worker SendVerificationMail authentication",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email : ",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/domain.UserResponse"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/worker/verify/account": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Varify OTP of users",
                "operationId": "Varify worker OTP authentication",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email : ",
                        "name": "email",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OTP : ",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "string"
                                        },
                                        "Errors": {
                                            "type": "string"
                                        },
                                        "Message": {
                                            "type": "string"
                                        },
                                        "Status": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Category": {
            "type": "object",
            "properties": {
                "contactnumber": {
                    "type": "string"
                },
                "idCategory": {
                    "type": "integer"
                }
            }
        },
        "domain.Login": {
            "type": "object",
            "properties": {
                "id_login": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "usertype": {
                    "type": "string"
                },
                "verification": {
                    "type": "string"
                }
            }
        },
        "domain.Profile": {
            "type": "object",
            "properties": {
                "contactnumber": {
                    "type": "string"
                },
                "dateofbirth": {
                    "type": "string"
                },
                "emailid": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "housename": {
                    "type": "string"
                },
                "idLogin": {
                    "type": "integer"
                },
                "idUser": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "photo": {
                    "type": "string"
                },
                "pin": {
                    "type": "string"
                },
                "place": {
                    "type": "string"
                },
                "post": {
                    "type": "string"
                }
            }
        },
        "domain.UserResponse": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "errors": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go + Gin Workey API",
	Description:      "This is a sample server Job Portal server. You can visit the GitHub repository at https://github.com/fazil/Job_Portal_Project",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
